set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER /home/builder/llvm/bin/clang)
set(CMAKE_CXX_COMPILER /home/builder/llvm/bin/clang++)
set(CMAKE_AR /home/builder/llvm/bin/llvm-ar)
set(CMAKE_RANLIB /home/builder/llvm/bin/llvm-ranlib)
set(CMAKE_STRIP /home/builder/llvm/bin/llvm-strip)
set(CMAKE_LINKER /home/builder/llvm/bin/lld)
set(CMAKE_C_COMPILER_TARGET aarch64-unknown-none-musl)
set(CMAKE_CXX_COMPILER_TARGET aarch64-unknown-none-musl)
set(CMAKE_EXE_LINKER_FLAGS "-static -nostdlib -fuse-ld=lld")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_CROSSCOMPILING TRUE)